version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/startapp-video
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  nginx:
    image: nginx:1.29.0 
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html

